version: "3.9"

services:
  bot:
    build: .
    container_name: weather_bot
    restart: always
    command: python ./bot.py
    environment:
      BOT_TOKEN: <токен бота без ковычек>
    networks:
      - weathe_bot_network

networks:
  weathe_bot_network:
    #external: true
    name: weathe_bot_network